// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package processor

import (
	"github.com/conduitio/conduit-commons/config"
)

func (llmEmbedConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		"source": {
			Default:     "",
			Description: "Field is the target field that will be set.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"target": {
			Default:     "",
			Description: "Name is the value of the field to add.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
